apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: shklnrj/railskube:latest
        env:
        - name: COUNTRY
          value: India
        ports:
        - containerPort: 3000
